# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8IaGh31E8h2EkwhDwg5GGFYpY4-SNhJ
"""

#Muhammad Ali Arshad Malik
#Fractal Image

"""
==================================================================
 STATIC MULTICOLORED JULIA SET FRACTAL (high-res PNG)
==================================================================

This is the code that generated the "julia_fractal.png" image shown
earlier -- a single, high-resolution, multicolored frame of the
Julia set fractal (rather than the animated version).

WHAT THIS PROGRAM DOES
-----------------------
This renders a *Julia Set* fractal -- a close cousin of the famous
Mandelbrot Set. Both come from repeatedly applying the same simple
rule to complex numbers:

        z_(n+1) = z_n^2 + c

    - For the MANDELBROT set, z starts at 0 and 'c' is the pixel
      coordinate (varies across the image, fixed per pixel).
    - For the JULIA set (what we draw here), 'c' is FIXED for the
      whole image, and 'z' starts at the pixel coordinate itself.

We iterate this formula for every pixel (treated as a complex number)
a fixed number of times. If a value "escapes" (its magnitude grows
past 2), we color that pixel based on HOW QUICKLY it escaped. Points
that never escape belong to the Julia set itself and are colored
black. This "escape time" coloring is what produces the swirling,
self-similar fractal patterns.

WHY IT'S MULTICOLORED
-----------------------
Escape-time values are mapped through an HSV (Hue-Saturation-Value)
color wheel, cycled a few times across the range of escape counts.
This turns the plain black-and-white "did it escape or not" data
into vivid rainbow contour bands.

REQUIREMENTS
-------------
    pip install numpy matplotlib

HOW TO RUN
-----------
    python julia_fractal_static.py

This saves "julia_fractal.png" in the current folder. (In Google
Colab, just paste this whole file into a cell and run it -- the
image will render inline automatically since Colab displays the
last plt figure by default; or call plt.show() if you prefer to see
it before it's saved.)

KEY CS IDEAS DEMONSTRATED
---------------------------
    - Recursion / iteration (the z = z^2 + c loop)
    - Self-similarity (zoom into any region -> similar structure)
    - Vectorized numeric computation with NumPy (fast, whole-image
      math instead of slow per-pixel Python loops)
==================================================================
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors


# ------------------------------------------------------------------
# 1. CONFIGURATION -- feel free to tweak these to explore the fractal
# ------------------------------------------------------------------

WIDTH, HEIGHT = 1200, 1200    # output image resolution in pixels
MAX_ITER = 300                 # how many times we apply z = z^2 + c
                                # before giving up on a point (higher
                                # = more detail, but slower)
ZOOM = 1.4                     # how "zoomed in" the view is
                                # (smaller number = more zoomed in)

# 'c' is fixed for a static image. This particular value (a point on
# a circle of radius 0.7885, at angle 2.5 radians) is a well-known
# "sweet spot" that produces a rich, dendrite-like Julia set shape.
C_RADIUS = 0.7885
C_ANGLE = 2.5
C = C_RADIUS * np.exp(1j * C_ANGLE)

# The complex-plane window we render (centered at 0,0)
X_MIN, X_MAX = -ZOOM, ZOOM
Y_MIN, Y_MAX = -ZOOM, ZOOM


# ------------------------------------------------------------------
# 2. BUILD THE COORDINATE GRID
# ------------------------------------------------------------------
# Create a 2D grid of complex numbers, one per pixel. Each pixel's
# (x, y) position becomes the REAL and IMAGINARY part of a complex
# number z = x + iy. This grid is what we iterate on.

x = np.linspace(X_MIN, X_MAX, WIDTH)
y = np.linspace(Y_MIN, Y_MAX, HEIGHT)
X, Y = np.meshgrid(x, y)
Z = X + 1j * Y   # Z.shape == (HEIGHT, WIDTH), dtype = complex


# ------------------------------------------------------------------
# 3. COMPUTE THE ESCAPE-TIME FRACTAL
# ------------------------------------------------------------------
# For every point in the grid, repeatedly apply z = z^2 + c and
# record how many iterations it took to "escape" (|z| > 2). This is
# fully VECTORIZED with NumPy: instead of a slow Python for-loop over
# every one of the WIDTH*HEIGHT pixels, we update the *entire grid at
# once* on each iteration, which is dramatically faster.

escape_counts = np.zeros(Z.shape, dtype=int)     # result buffer
still_bounded = np.ones(Z.shape, dtype=bool)     # which pixels haven't escaped yet

for i in range(MAX_ITER):
    # --- THE CORE FRACTAL RECURRENCE ---
    # Only update points that haven't escaped yet (saves time and
    # avoids numeric overflow on already-diverged points).
    Z[still_bounded] = Z[still_bounded] ** 2 + C

    # A point has "escaped" once its distance from the origin
    # exceeds 2 (the standard escape radius -- once |z| > 2 the
    # sequence is mathematically guaranteed to run away to infinity).
    escaped_now = np.abs(Z) > 2

    # Points escaping on THIS iteration get their escape time
    # recorded (only the ones that were still bounded before).
    newly_escaped = escaped_now & still_bounded
    escape_counts[newly_escaped] = i

    # Remove newly-escaped points from the "still bounded" set so we
    # stop iterating on them.
    still_bounded &= ~escaped_now

    # Early exit: if literally every pixel has escaped, no point
    # continuing the loop.
    if not still_bounded.any():
        break

# Anything still bounded at the end belongs to the Julia set itself.
escape_counts[still_bounded] = MAX_ITER


# ------------------------------------------------------------------
# 4. COLOR THE RESULT WITH AN HSV RAINBOW WHEEL
# ------------------------------------------------------------------
# - HUE cycles smoothly with the escape count, producing rainbow
#   bands that trace the fractal's contour lines.
# - SATURATION and VALUE are kept high so colors look vibrant, except
#   points that never escaped (part of the true Julia set), which we
#   force to pure black for visual contrast.

normalized = escape_counts / escape_counts.max()
hue = (normalized * 3.0) % 1.0        # * 3 cycles the rainbow a few
                                       # times for tighter, more
                                       # colorful bands
saturation = np.full_like(hue, 0.85)
value = np.where(escape_counts >= MAX_ITER, 0.0, 1.0)  # black for "in the set"

hsv_image = np.dstack((hue, saturation, value))
rgb_image = mcolors.hsv_to_rgb(hsv_image)


# ------------------------------------------------------------------
# 5. RENDER AND SAVE
# ------------------------------------------------------------------

fig, ax = plt.subplots(figsize=(10, 10))
fig.patch.set_facecolor("black")
ax.imshow(rgb_image, extent=(X_MIN, X_MAX, Y_MIN, Y_MAX), interpolation="bilinear")
ax.set_xticks([])
ax.set_yticks([])
ax.set_title(
    f"Julia Set  (c = {C.real:.3f} + {C.imag:.3f}i)",
    color="white", fontsize=14, pad=10,
)

plt.tight_layout()
plt.savefig("julia_fractal.png", dpi=150, facecolor="black")
plt.show()

print("Saved julia_fractal.png")